services:
  - type: web
    name: Job-requirements-api
    env: python
    runtime:
      version: '3.11'
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    port: 8000
    healthCheck:
      path: /
